# Generated by Django 5.1.6 on 2025-03-27 23:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_joined', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, null=True)),
                ('telefone', models.IntegerField()),
                ('sobrenome', models.CharField(max_length=255, null=True)),
                ('cpf', models.CharField(max_length=11)),
                ('cnpj', models.CharField(max_length=18)),
                ('email', models.CharField(max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('codigoDeBarra', models.CharField(max_length=50, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('cnpj', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=30)),
                ('nomeEmpresa', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_emitente', models.CharField(max_length=14)),
                ('cnpj_destinatario', models.CharField(max_length=14)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('chave_nfe', models.CharField(max_length=44, unique=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idproduto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.FloatField()),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('controlado', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('formaDePagamento', models.CharField(max_length=50)),
                ('codigoDeBarraFatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fatura', to_field='codigoDeBarra')),
            ],
        ),
        migrations.CreateModel(
            name='Financas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fatura', models.ManyToManyField(to='app.fatura')),
                ('pagamento', models.ManyToManyField(to='app.pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('motivo', models.CharField(max_length=11)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idproduto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
            ],
        ),
        migrations.CreateModel(
            name='RecebimentoMercadoria',
            fields=[
                ('idrecebeu', models.AutoField(primary_key=True, serialize=False)),
                ('datarecebeu', models.DateField(default=datetime.date.today)),
                ('totalproduto', models.IntegerField()),
                ('notaFiscal', models.IntegerField()),
                ('cnpj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fornecedor')),
                ('idproduto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
            ],
        ),
        migrations.CreateModel(
            name='SaidaMercadoria',
            fields=[
                ('idsaida', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datacompra', models.DateField(default=datetime.date.today)),
                ('idproduto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
            ],
        ),
    ]
